name: laendle_guessr
description: "Ein Standort-basiertes Flutter-Quiz-Spiel im Stil von GeoGuessr."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  flutter_native_splash: ^2.4.0

  provider: ^6.1.3
  pedometer: ^4.0.0


  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/elkin.png
    - assets/images/riddle.png
    - assets/images/ursa.png
    - assets/images/aster.png
    - assets/images/foxrot.png
    - assets/images/fritz.png
