openapi: 3.0.0
info:
  description: Eine API zur Verbindung mit unserer Supabase-Datenbank
  title: LaendleGuessr
  version: 1.0.0
servers:
  - url: /

paths:
  /all_item_user/{uid}:
    get:
      operationId: all_items_owned_by
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Alle Items eines Users bekommen
      tags:
        - item
      x-openapi-router-controller: openapi_server.controllers.item_controller

  /all_quests:
    get:
      operationId: all_quests_get
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Alle Quests bekommen
      tags:
        - quest
      x-openapi-router-controller: openapi_server.controllers.quest_controller

  /all_quests_user/{uid}:
    get:
      operationId: all_quests_done_by
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Alle gemachten Quests eines Users bekommen
      tags:
        - quest
      x-openapi-router-controller: openapi_server.controllers.quest_controller

  /dailyquest/{city}:
    get:
      operationId: dailyquest_get
      parameters:
        - in: path
          name: city
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Derzeitige DailyQuest einer Stadt
      tags:
        - quest
      x-openapi-router-controller: openapi_server.controllers.quest_controller
  /activequest/{uid}:
    get:
      operationId: activequest_get
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Aktive Quest eines Users abrufen
      tags:
        - quest
      x-openapi-router-controller: openapi_server.controllers.quest_controller
    delete:
      operationId: activequest_delete
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Erfolgreich entfernt
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Aktive Quest eines Users entfernen
      tags:
        - quest
      x-openapi-router-controller: openapi_server.controllers.quest_controller
  /activequest:
    post:
      operationId: activequest_post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                uid:
                  type: integer
                qid:
                  type: integer
              required:
                - uid
                - qid
      responses:
        "200":
          description: Erfolgreich hinzugefügt
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Aktive Quest für User setzen
      tags:
        - quest
      x-openapi-router-controller: openapi_server.controllers.quest_controller
  /quest/{qid}:
    get:
      operationId: quest_get
      parameters:
        - in: path
          name: qid
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Quest mit bestimmter ID anzeigen
      tags:
        - quest
      x-openapi-router-controller: openapi_server.controllers.quest_controller

  /item:
    get:
      operationId: all_items_get
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Alle Items anzeigen
      tags:
        - item
      x-openapi-router-controller: openapi_server.controllers.item_controller

  /item/{id}:
    get:
      operationId: item_get
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Item mit bestimmter ID anzeigen
      tags:
        - item
      x-openapi-router-controller: openapi_server.controllers.item_controller

  /item_user:
    post:
      operationId: item_user_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_id'
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Einem User ein Item zuschreiben
      tags:
        - item
      x-openapi-router-controller: openapi_server.controllers.item_controller

  /quest_user:
    post:
      operationId: quest_user_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_id'
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Einem User eine Quest als gemacht zuschreiben
      tags:
        - quest
      x-openapi-router-controller: openapi_server.controllers.quest_controller

  /user:
    get:
      operationId: all_users_get
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Alle User anzeigen
      tags:
        - user
      x-openapi-router-controller: openapi_server.controllers.user_controller
    post:
      operationId: user_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Neuen User hinzufügen
      tags:
        - user
      x-openapi-router-controller: openapi_server.controllers.user_controller

  /user/{id}:
    get:
      operationId: user_get
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: User mit bestimmter ID anzeigen
      tags:
        - user
      x-openapi-router-controller: openapi_server.controllers.user_controller
    put:
      operationId: user_update
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: User bearbeiten
      tags:
        - user
      x-openapi-router-controller: openapi_server.controllers.user_controller

  /weeklyquest:
    get:
      operationId: weeklyquest_get
      responses:
        "200":
          description: Erfolgreiche Antwort
        "400":
          description: Ungültige Eingabe
        "503":
          description: Service nicht verfügbar
      summary: Derzeitige globale WeeklyQuest
      tags:
        - quest
      x-openapi-router-controller: openapi_server.controllers.quest_controller

components:
  schemas:
    user_id:
      title: user_id
      required:
        - uid
        - id
      properties:
        uid:
          type: integer
          minimum: 1
          title: UserID
        id:
          type: integer
          minimum: 1
          title: ID
      example:
        uid: 3
        id: 4

    user:
      title: user
      required:
        - username
        - password
        - coins
        - admin
        - city
      properties:
        username:
          type: string
          title: Benutzername
          minLength: 3
          maxLength: 30
        password:
          type: string
          title: Passwort
        coins:
          type: integer
          title: Coins
          minimum: 0
        admin:
          type: boolean
          title: Admin
        city:
          type: integer
          title: Stadt
          enum:
            - 0  
            - 1  
            - 2  
            - 3  
            - 4  
      example:
        username: keremderkomet
        password: MeinSicheresPasswort123
        coins: 150
        admin: true
        city: 1
